import sys
import os
import json
import asyncio
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "backend")))

from fastapi.testclient import TestClient
from main import app

def test_alerts_monitoring_e2e():
    print("Starting Autonomous Credit Monitoring E2E integration test...")
    client = TestClient(app)

    wallet = "0x5bb83E60a7a05A0e1b077B66412a26306e334208"

    # Step 1: Create a manual alert to initialize
    print("Step 1: Creating a test credit alert...")
    from app.services.alert_engine import AlertEngine
    engine = AlertEngine()
    alert = engine.create_alert(
        wallet=wallet,
        alert_type="CREDIT_CHANGE",
        severity="HIGH",
        title="E2E Credit Drop Simulation",
        description="Manual alert trigger simulation.",
        recommendation="Clear active leverages.",
        source="TestSuit"
    )
    assert alert["alert_id"].startswith("alt_")
    alert_id = alert["alert_id"]

    # Step 2: GET /alerts/{wallet}
    print("Step 2: Retrieving active alerts list...")
    list_resp = client.get(f"/alerts/{wallet}")
    assert list_resp.status_code == 200, list_resp.text
    alerts_list = list_resp.json()
    print("Alerts:")
    print(alerts_list)
    assert len(alerts_list) > 0
    assert any(a["alert_id"] == alert_id for a in alerts_list)

    # Step 3: POST /alerts/monitor/{wallet}
    print("Step 3: Executing live monitoring snapshot scan...")
    # Seed snapshot initial state
    snapshots = {wallet.lower(): {"credit_score": 750, "risk_level": "LOW"}}
    from app.database.persistence import write_json
    write_json("snapshots.json", snapshots)

    mon_resp = client.post(f"/alerts/monitor/{wallet}")
    assert mon_resp.status_code == 200, mon_resp.text
    new_alerts = mon_resp.json()
    print("New alerts generated by snapshot shift:")
    print(new_alerts)
    assert len(new_alerts) > 0
    assert any(a["alert_type"] == "CREDIT_CHANGE" and a["severity"] == "HIGH" for a in new_alerts)

    # Step 4: GET /alerts/system
    print("Step 4: Fetching systemic alerts list...")
    sys_resp = client.get("/alerts/system")
    assert sys_resp.status_code == 200, sys_resp.text
    sys_list = sys_resp.json()
    print(f"Total system alerts logs: {len(sys_list)}")
    assert len(sys_list) > 0

    # Step 5: POST /alerts/resolve/{alert_id}
    print("Step 5: Resolving active alert...")
    res_resp = client.post(f"/alerts/resolve/{alert_id}")
    assert res_resp.status_code == 200, res_resp.text
    assert res_resp.json()["resolved"] is True

    # Step 6: Test SSE stream connection generator directly
    print("Step 6: Opening Server Sent Events (SSE) stream...")
    from app.api.alerts import stream_wallet_alerts
    streaming_response = stream_wallet_alerts(wallet)
    
    async def read_ping():
        # Get the first event from the generator
        async for item in streaming_response.body_iterator:
            return item

    loop = asyncio.new_event_loop()
    ping_line = loop.run_until_complete(read_ping())
    print(f"Stream output line: {ping_line}")
    assert ping_line.startswith("data: ")
    ping_event = json.loads(ping_line[6:])
    assert ping_event["status"] == "CONNECTED"
    loop.close()

    print("All Autonomous Credit Monitoring integration checks passed successfully!")

if __name__ == "__main__":
    test_alerts_monitoring_e2e()
